name: 'Get Hot Repos'
description: 'Get the repos you most recently committed to.'
author: 'Zachary Cauchi'
inputs:
  token:
    required: true
    description: 'Your github personal access token. Usually, just need to set it to your GITHUB_TOKEN in the workflow.'
outputs:
  topRepos:
    description: 'The top repos reported by the action. Repos are sorted in descending order based on the date of the last commit.'
runs:
  using: 'node16'
  main: 'dist/index.js'
