name: 'Get Hot Repos'
description: 'Get the repos you most recently committed to.'
author: 'Zachary Cauchi'
branding:
  icon: trending-up
  color: green

inputs:
  token:
    required: true
    description: 'Your github personal access token. Usually, just need to set it to your GITHUB_TOKEN in the workflow.'
  entryCount:
    description: 'How many repos to fetch from your list.'
    required: false
    default: '5'
  sortOrder:
    description: |
      Whether to sort in ascending order or descending order.
      Accepted values:
      ascending | asc
      descending | desc
    required: false
    default: desc
  jsonFilepath:
    description: |
      The path to the file for writing the generated json.
      If you'd like to not save to a file, set this to an empty string ('') or ignore it.
    required: false
    default: ''
  mdHeader:
    description: |
      A header for the generated markdown file.
      If you aren't using markdown, this field can be ignored.
    required: false
    default: ''
  mdListTemplate:
    description: |
      A template list entry for each element in the list.
      Each field in the `topRepos` output is assigned a replacer which will be searched for in the template.
      When a replacer is found, it is substituted with the value from the `topRepos` entry being processed.
      If you aren't using markdown, this field can be ignored.
    required: false
    default: '* [{{REPO}}]({{REPOURL}}) ([{{COMMITMSG}}]({{COMMITURL}}))'
  mdFilepath:
    description: |
      The path to the file for writing the generated markdown.
      If you'd like to not save to a file, set this to an empty string ('') or ignore it.
      If you aren't using markdown, this field can be ignored.
    required: false
    default: ''
  generateMarkdown:
    description: 'Whether to generate a markdown output or not. Set to false to disable markdown output'
    required: false
    default: true

outputs:
  topRepos:
    description: 'The top repos reported by the action. Repos are sorted in descending order based on the date of the last commit.'
  markdown:
    description: |
      The generated markdown for the obtained repos.
      This is only set if `generateMarkdown` is true.
runs:
  using: 'node16'
  main: 'dist/index.js'
