name: 'Get Hot Repos'
description: 'Get the repos you most recently committed to.'
author: 'Zachary Cauchi'
inputs:
  token:
    required: true
    description: 'Your github personal access token. Usually, just need to set it to \'${{ secrets.GITHUB_TOKEN }}\''
runs:
  using: 'node16'
  main: 'dist/index.js'
