# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate this file through a build process from other source files.
# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
name: Check dist/

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set Node.js 16.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: |
          npm run build
          npm run package

      - name: Compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ ':!*.map' | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            echo "::set-output name=commit_dist::true"

            exit 0
          fi
        id: diff

      # If index.js was updated, we want to commit the updated one automatically.
      - uses: EndBug/add-and-commit@v9
        with:
          add: dist
          default_author: github_actions
          message: 'feat: update dist package'
      
      # - name: Commit updated dist
      #   if: ${{ steps.diff.outputs.commit_dist == 'true' }}
      #   run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add dist
      #     git commit -am "feat: update dist"
      #     git push

      #     # We don't want to upload artifacts if we just committed. We want the artifact to be uploaded with a new run.
      #     echo "::set-output name=upload_artifact::true"

      - uses: actions/upload-artifact@v3
        if: ${{ steps.diff.outputs.upload_artifact == 'true' }}
        with:
          name: dist
          path: dist/
