name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
      - 'feature/*'
  
  workflow_dispatch:

permissions: read-all # This is necessary for appropriate permissions to be granted.

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: ./
        id: test
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # token: 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
      
      - name: Check output of actions
        run: |
          echo Printing action output
          echo ${{ steps.test.outputs.topRepos }}
          echo printing complete
        id: post
